### PR TITLE
Milestone 2 refactor

### PR DESCRIPTION
**Pull request by jcockhren**
This PR combines milestones 1 and 2. Databases is the new milestone 2.

Foundations now has a `mastery` directory quizzes

@chortlehoort

### CODE REVIEW

**Comment by chortlehoort** [comment]
Can you provide more details about why you feel the merge is needed? Removing the milestone impacts more than just the structure of the repo, but also changes how we collect feedback from students because the Node and the Python milestones still have the CLI section.

Just to provide some additional context, I've made enhancements to the CLI milestone during the Python course to cover more material which I was intending on migrating over the C#.

The intent for the Foundations milestone was to introduce the students to the language, tools, development concepts and unit tests.

**Comment by chortlehoort** [comment]
This large of a change requires some discussion with the entire team before it's merged

**Comment by jcockhren** [comment]
@chortlehoort 
When we spoke about this change some while ago (towards the beginning/middle of milestone 1), where milestone 2 as it stood, made more sense to be rolled into the the first milestone given it's length and that CLI is covered as a result of the exercises in the first milestone.

I'll do better with getting approval before shifting the milestones around,

**Comment by chortlehoort** [comment]
Here's an thought. Let's try to find a time where you, Scott, Denise, and myself can sit and discuss the first two milestones and see what makes sense. Take a look at what we defined for the 2nd milestone in the Python class (https://github.com/nashville-software-school/python-milestones/tree/master/02-command-line-applications). It's got a lot more meat on its bones.

My thought was that the CLI milestone would prepare them for DB by introducing serialization and relating objects together.

Let me see what I can schedule with everyone.

**Pull request merged**
